services:
  app:
    image: itdaily-admin:latest
    container_name: itdaily-admin
    ports:
      - "127.0.0.1:7000:7000"
    restart: always
    env_file: .env.prod
    environment:
      - NODE_ENV=production
      - PORT=7000
    command: npm run start:prod # override for hot-reload
